-- Language learning layer.
--
-- A study pack is derived from one subtitle track and is identical for every
-- viewer, so it is stored once per (title, episode, language) and shared. What
-- differs per person lives in user_word, which is a small set of lemmas.

CREATE TABLE study_pack (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_key   varchar(120) NOT NULL,
    episode     integer NOT NULL,
    lang        varchar(8) NOT NULL,
    line_count  integer NOT NULL,
    word_count  integer NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL
);

CREATE UNIQUE INDEX ux_study_pack_slot ON study_pack (anime_key, episode, lang);

CREATE TABLE study_word (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id        bigint NOT NULL,
    lemma          varchar(120) NOT NULL,
    surface        varchar(120),
    pos            varchar(24),
    zipf           real NOT NULL,
    level          smallint NOT NULL,
    occurrences    integer NOT NULL,
    first_line     integer NOT NULL,
    sample_line    varchar(500),
    CONSTRAINT fk_study_word_pack FOREIGN KEY (pack_id) REFERENCES study_pack (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_study_word_slot ON study_word (pack_id, lemma);
CREATE INDEX ix_study_word_level ON study_word (pack_id, level);

-- Which languages a person is learning, and how strong they are in each.
CREATE TABLE user_language (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL,
    lang       varchar(8) NOT NULL,
    role       varchar(12) NOT NULL,
    level      smallint NOT NULL DEFAULT 1,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT user_language_role_check CHECK (role IN ('LEARNING', 'NATIVE')),
    CONSTRAINT user_language_level_check CHECK (level BETWEEN 1 AND 6),
    CONSTRAINT fk_user_language_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE UNIQUE INDEX ux_user_language ON user_language (user_id, lang);

-- The personal dictionary. One row per lemma the learner has an opinion about;
-- everything they have never touched is simply absent.
CREATE TABLE user_word (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint NOT NULL,
    lang          varchar(8) NOT NULL,
    lemma         varchar(120) NOT NULL,
    status        varchar(12) NOT NULL,
    times_seen    integer NOT NULL DEFAULT 1,
    note          varchar(500),
    context_line  varchar(500),
    anime_key     varchar(120),
    episode       integer,
    time_sec      integer,
    created_at    timestamp(6) with time zone NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    CONSTRAINT user_word_status_check CHECK (status IN ('NEW', 'LEARNING', 'KNOWN', 'IGNORED')),
    CONSTRAINT fk_user_word_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE UNIQUE INDEX ux_user_word_slot ON user_word (user_id, lang, lemma);
CREATE INDEX ix_user_word_status ON user_word (user_id, lang, status);
