-- Spaced repetition state, kept on the word itself: there is exactly one
-- schedule per (user, lemma), and reviews are the append-only history.
ALTER TABLE user_word ADD COLUMN due_at        timestamp(6) with time zone;
ALTER TABLE user_word ADD COLUMN interval_days real NOT NULL DEFAULT 0;
ALTER TABLE user_word ADD COLUMN ease          real NOT NULL DEFAULT 2.5;
ALTER TABLE user_word ADD COLUMN reps          integer NOT NULL DEFAULT 0;
ALTER TABLE user_word ADD COLUMN lapses        integer NOT NULL DEFAULT 0;
ALTER TABLE user_word ADD COLUMN last_review_at timestamp(6) with time zone;

-- Anything already marked "learning" becomes due immediately, so an existing
-- dictionary turns into a first review session instead of staying inert.
UPDATE user_word SET due_at = now() WHERE status = 'LEARNING' AND due_at IS NULL;

CREATE INDEX ix_user_word_due ON user_word (user_id, lang, due_at);

CREATE TABLE word_review (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,
    lang        varchar(8) NOT NULL,
    lemma       varchar(120) NOT NULL,
    grade       smallint NOT NULL,
    correct     boolean NOT NULL,
    elapsed_ms  integer,
    reviewed_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT word_review_grade_check CHECK (grade BETWEEN 0 AND 3),
    CONSTRAINT fk_word_review_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE INDEX ix_word_review_recent ON word_review (user_id, lang, reviewed_at DESC);
