-- Payment intents and the provider callback log.
--
-- Two tables because they answer two different questions. An intent is "this user
-- asked to buy this plan", created before the user leaves for the payment page —
-- without it a callback would have to be trusted about who is paying for what.
-- An event is "the provider told us something", stored verbatim and exactly once:
-- providers retry callbacks for hours, so idempotency is a unique index, not a
-- best effort, and the raw body is kept because a payment dispute is argued from
-- what the provider actually sent, not from our interpretation of it.
CREATE TABLE payment_intents (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             bigint NOT NULL,
    plan                varchar(16) NOT NULL,
    provider            varchar(32) NOT NULL,
    provider_payment_id varchar(160),
    amount_minor        integer NOT NULL,
    currency            varchar(8) NOT NULL,
    status              varchar(16) NOT NULL,
    created_at          timestamp(6) with time zone NOT NULL,
    updated_at          timestamp(6) with time zone,
    CONSTRAINT payment_intents_plan_check
        CHECK (plan IN ('MONTHLY', 'YEARLY', 'LIFETIME')),
    CONSTRAINT payment_intents_status_check
        CHECK (status IN ('CREATED', 'PENDING', 'SUCCEEDED', 'CANCELED', 'FAILED')),
    CONSTRAINT payment_intents_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT fk_payment_intents_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE INDEX ix_payment_intents_user ON payment_intents (user_id, created_at DESC);

-- The provider's id is how a callback finds its intent, so it must resolve to one.
CREATE UNIQUE INDEX ux_payment_intents_provider_payment
    ON payment_intents (provider, provider_payment_id)
    WHERE provider_payment_id IS NOT NULL;

CREATE TABLE payment_events (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          varchar(32) NOT NULL,
    provider_event_id varchar(200) NOT NULL,
    kind              varchar(48) NOT NULL,
    intent_id         bigint,
    user_id           bigint,
    outcome           varchar(16) NOT NULL,
    note              varchar(400),
    payload           text NOT NULL,
    received_at       timestamp(6) with time zone NOT NULL,
    CONSTRAINT payment_events_outcome_check
        CHECK (outcome IN ('APPLIED', 'DUPLICATE', 'IGNORED', 'REJECTED')),
    CONSTRAINT fk_payment_events_intent FOREIGN KEY (intent_id) REFERENCES payment_intents (id)
);

-- Idempotency: the second delivery of the same event is a no-op by construction.
CREATE UNIQUE INDEX ux_payment_events_provider_event
    ON payment_events (provider, provider_event_id);

CREATE INDEX ix_payment_events_received ON payment_events (received_at DESC);
