-- Per-user daily budget for the AI features.
--
-- The counter lives in the database rather than in memory because it guards money:
-- an in-process map resets on every deploy and is per-instance, so two replicas
-- would grant two budgets. One row per (user, day, kind) — the unique index is what
-- makes concurrent requests from the same account add up instead of racing.
CREATE TABLE ai_usage (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL,
    -- `day` is reserved (SQL interval qualifier), and quoting it differs between
    -- Postgres and the H2 the tests run on; the column carries a name instead.
    usage_day  date NOT NULL,
    kind       varchar(16) NOT NULL,
    units      integer NOT NULL DEFAULT 0,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ai_usage_kind_check CHECK (kind IN ('REVIEW', 'TRANSLATE')),
    CONSTRAINT ai_usage_units_positive CHECK (units >= 0),
    CONSTRAINT fk_ai_usage_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE UNIQUE INDEX ux_ai_usage_slot ON ai_usage (user_id, usage_day, kind);
