-- Advertising: campaigns, creatives, decisions and the impression log.
--
-- Four tables because four different questions get asked of them:
--
--   campaigns  — what an advertiser bought, and the legal identity behind it. The
--                INN and the ORD token are not metadata: under RF advertising law
--                every served impression has to be attributable and reportable, so
--                they live next to the money, not in a spreadsheet.
--   creatives  — the file that airs, with the rules of airing it (skip offset,
--                click target, disclaimer, age marker).
--   decisions  — "this viewer was told to play this creative". Written before the
--                ad airs, so an event arriving later has something to be matched
--                against; a decision is also the only place a user id and an ad
--                ever meet, which keeps the event log free of identity.
--   events     — append-only playback beacons. One row per (decision, kind): the
--                unique index is what makes retried beacons harmless, and beacons
--                WILL be retried because sendBeacon fires on tab close.
CREATE TABLE ad_campaigns (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 varchar(160) NOT NULL,
    advertiser           varchar(200) NOT NULL,
    -- Taxpayer id of the advertiser: 10 digits for a company, 12 for a sole trader.
    advertiser_inn       varchar(12) NOT NULL,
    status               varchar(16) NOT NULL,
    starts_at            timestamp(6) with time zone,
    ends_at              timestamp(6) with time zone,
    -- 0 means "no cap"; anything above it stops serving for the rest of the UTC day.
    daily_impression_cap integer NOT NULL DEFAULT 0,
    priority             integer NOT NULL DEFAULT 50,
    created_at           timestamp(6) with time zone NOT NULL,
    updated_at           timestamp(6) with time zone,
    CONSTRAINT ad_campaigns_status_check
        CHECK (status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED')),
    CONSTRAINT ad_campaigns_inn_check CHECK (advertiser_inn ~ '^[0-9]{10}([0-9]{2})?$'),
    CONSTRAINT ad_campaigns_cap_check CHECK (daily_impression_cap >= 0),
    CONSTRAINT ad_campaigns_priority_check CHECK (priority BETWEEN 0 AND 100),
    CONSTRAINT ad_campaigns_window_check CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE INDEX ix_ad_campaigns_serving ON ad_campaigns (status, priority DESC);

CREATE TABLE ad_creatives (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id      bigint NOT NULL,
    src              varchar(600) NOT NULL,
    duration_sec     integer NOT NULL,
    -- NULL means unskippable; otherwise the second at which Skip may appear.
    skip_after_sec   integer,
    click_url        varchar(600),
    -- ЕРИР/ОРД marking token. A creative without one must not air.
    ord_token        varchar(120),
    legal_disclaimer varchar(400),
    age_rating       integer,
    active           boolean NOT NULL DEFAULT true,
    created_at       timestamp(6) with time zone NOT NULL,
    updated_at       timestamp(6) with time zone,
    CONSTRAINT ad_creatives_duration_check CHECK (duration_sec > 0),
    CONSTRAINT ad_creatives_skip_check
        CHECK (skip_after_sec IS NULL OR (skip_after_sec >= 0 AND skip_after_sec <= duration_sec)),
    CONSTRAINT ad_creatives_age_check CHECK (age_rating IS NULL OR age_rating BETWEEN 0 AND 21),
    CONSTRAINT fk_ad_creatives_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns (id) ON DELETE CASCADE
);

CREATE INDEX ix_ad_creatives_campaign ON ad_creatives (campaign_id, active);

CREATE TABLE ad_decisions (
    id          varchar(36) PRIMARY KEY,
    creative_id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    user_id     bigint,
    anime_key   varchar(120),
    episode     integer,
    country     varchar(2),
    created_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_ad_decisions_creative FOREIGN KEY (creative_id) REFERENCES ad_creatives (id),
    CONSTRAINT fk_ad_decisions_campaign FOREIGN KEY (campaign_id) REFERENCES ad_campaigns (id)
);

CREATE INDEX ix_ad_decisions_created ON ad_decisions (created_at DESC);
CREATE INDEX ix_ad_decisions_campaign_day ON ad_decisions (campaign_id, created_at DESC);

CREATE TABLE ad_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id varchar(36) NOT NULL,
    campaign_id bigint NOT NULL,
    creative_id bigint NOT NULL,
    kind        varchar(16) NOT NULL,
    position_sec integer NOT NULL DEFAULT 0,
    created_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT ad_events_kind_check
        CHECK (kind IN ('START', 'Q25', 'Q50', 'Q75', 'COMPLETE', 'SKIP', 'CLICK')),
    CONSTRAINT fk_ad_events_decision FOREIGN KEY (decision_id) REFERENCES ad_decisions (id) ON DELETE CASCADE
);

-- One row per (decision, kind): a beacon that arrives twice must not inflate a
-- billable number.
CREATE UNIQUE INDEX ux_ad_events_decision_kind ON ad_events (decision_id, kind);

CREATE INDEX ix_ad_events_reporting ON ad_events (campaign_id, kind, created_at DESC);
