-- New-episode notifications for bookmarked titles.

-- Last episode count seen per title. The first observation only records the
-- number: a title bookmarked long ago must not announce its whole back catalogue.
CREATE TABLE anime_release_state (
    anime_id           bigint PRIMARY KEY,
    published_episodes integer NOT NULL,
    checked_at         timestamp(6) with time zone NOT NULL,
    CONSTRAINT anime_release_state_episodes_check CHECK (published_episodes >= 0),
    CONSTRAINT fk_anime_release_state_anime FOREIGN KEY (anime_id) REFERENCES animes (id) ON DELETE CASCADE
);

-- In-app inbox. One row per (user, title, episode): the unique index makes a
-- re-run of the watcher after a crash harmless.
CREATE TABLE notifications (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,
    kind        varchar(24) NOT NULL,
    anime_id    bigint NOT NULL,
    anime_title varchar(255) NOT NULL,
    episode     integer NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    read_at     timestamp(6) with time zone,
    CONSTRAINT notifications_kind_check CHECK (kind IN ('NEW_EPISODE')),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_notifications_episode ON notifications (user_id, kind, anime_id, episode);
CREATE INDEX ix_notifications_inbox ON notifications (user_id, created_at DESC);

-- Opt-out for the email digest; the in-app inbox is always on.
ALTER TABLE app_users ADD COLUMN episode_emails boolean NOT NULL DEFAULT true;
