-- Baseline of the schema previously generated by Hibernate ddl-auto=update.
-- Captured with pg_dump --schema-only; from here on the schema is migration-owned
-- and Hibernate runs in validate mode.

CREATE TABLE anime_categories (
    anime_id bigint NOT NULL,
    category_id bigint NOT NULL
);

CREATE TABLE animes (
    id bigint NOT NULL,
    creation_date timestamp(6) without time zone,
    creator_user_id bigint,
    image_url character varying(255),
    is_deleted boolean NOT NULL,
    mal_id bigint,
    rating double precision,
    synopsis character varying(2000),
    title character varying(255)
);

ALTER TABLE animes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME animes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE app_users (
    id bigint NOT NULL,
    avatar_url character varying(255),
    banner_url character varying(255),
    bio character varying(600),
    birthday date,
    comments_count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(255),
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    failed_attempts integer NOT NULL,
    friends integer NOT NULL,
    is_deleted boolean NOT NULL,
    last_login_at timestamp(6) with time zone,
    level integer NOT NULL,
    likes integer NOT NULL,
    location character varying(255),
    locked_until timestamp(6) with time zone,
    password_hash character varying(255) NOT NULL,
    points integer NOT NULL,
    posts integer NOT NULL,
    profile_views integer NOT NULL,
    role character varying(16) NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT app_users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE categories (
    id bigint NOT NULL,
    creation_date timestamp(6) without time zone,
    is_deleted boolean NOT NULL,
    name character varying(120) NOT NULL
);

ALTER TABLE categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE comments (
    id bigint NOT NULL,
    author_name character varying(255),
    author_role character varying(255),
    creation_date timestamp(6) without time zone,
    creator_user_id bigint,
    description character varying(2000) NOT NULL,
    is_deleted boolean NOT NULL,
    anime_id bigint NOT NULL
);

ALTER TABLE comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    family_id character varying(36) NOT NULL,
    ip_address character varying(64),
    replaced_by_hash character varying(64),
    revoked boolean NOT NULL,
    token_hash character varying(64) NOT NULL,
    user_agent character varying(512),
    user_id bigint NOT NULL
);

ALTER TABLE refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE verification_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    type character varying(24) NOT NULL,
    used_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    CONSTRAINT verification_tokens_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL_VERIFY'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);

ALTER TABLE verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE watch_events (
    id bigint NOT NULL,
    anime_key character varying(255),
    anime_title character varying(255),
    episode integer NOT NULL,
    provider character varying(255),
    user_email character varying(255),
    user_id bigint,
    user_name character varying(255),
    watched_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE watch_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME watch_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY anime_categories
    ADD CONSTRAINT anime_categories_pkey PRIMARY KEY (anime_id, category_id);

ALTER TABLE ONLY animes
    ADD CONSTRAINT animes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

ALTER TABLE ONLY app_users
    ADD CONSTRAINT ux_app_users_email UNIQUE (email);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT ux_refresh_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY verification_tokens
    ADD CONSTRAINT ux_verification_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY verification_tokens
    ADD CONSTRAINT verification_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY watch_events
    ADD CONSTRAINT watch_events_pkey PRIMARY KEY (id);

CREATE INDEX ix_refresh_family ON refresh_tokens USING btree (family_id);

CREATE INDEX ix_watch_events_anime ON watch_events USING btree (anime_key);

CREATE INDEX ix_watch_events_user ON watch_events USING btree (user_id);

CREATE INDEX ix_watch_events_watched_at ON watch_events USING btree (watched_at);

ALTER TABLE ONLY anime_categories
    ADD CONSTRAINT fkicqnbisf4mbbp2211md3d80rm FOREIGN KEY (anime_id) REFERENCES animes(id);

ALTER TABLE ONLY comments
    ADD CONSTRAINT fkjnec39rsoed2ry9jx2njy0ej6 FOREIGN KEY (anime_id) REFERENCES animes(id);

ALTER TABLE ONLY anime_categories
    ADD CONSTRAINT fkn2myc6sbxttytkn7ptbts4xci FOREIGN KEY (category_id) REFERENCES categories(id);
