-- Subscription entitlements. A user is ads-free while an ACTIVE row exists whose
-- current_period_end is either NULL (lifetime purchase) or still in the future.
CREATE TABLE subscriptions (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  bigint NOT NULL,
    plan                     varchar(16) NOT NULL,
    status                   varchar(16) NOT NULL,
    current_period_end       timestamp(6) with time zone,
    cancel_at_period_end     boolean NOT NULL DEFAULT false,
    provider                 varchar(32) NOT NULL,
    provider_subscription_id varchar(128),
    created_at               timestamp(6) with time zone NOT NULL,
    updated_at               timestamp(6) with time zone,
    CONSTRAINT subscriptions_plan_check
        CHECK (plan IN ('MONTHLY', 'YEARLY', 'LIFETIME')),
    CONSTRAINT subscriptions_status_check
        CHECK (status IN ('PENDING', 'ACTIVE', 'CANCELED', 'EXPIRED')),
    CONSTRAINT subscriptions_lifetime_has_no_period
        CHECK (plan <> 'LIFETIME' OR current_period_end IS NULL),
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE INDEX ix_subscriptions_user ON subscriptions (user_id);

-- One live subscription per user; historical rows (CANCELED/EXPIRED) are unconstrained.
CREATE UNIQUE INDEX ux_subscriptions_user_live
    ON subscriptions (user_id)
    WHERE status IN ('PENDING', 'ACTIVE');

-- Provider-side id must map to at most one local subscription (webhook idempotency).
CREATE UNIQUE INDEX ux_subscriptions_provider_id
    ON subscriptions (provider, provider_subscription_id)
    WHERE provider_subscription_id IS NOT NULL;
