-- Federated identities. The provider's subject claim ("sub") is the identity
-- key, never the email address: emails change hands, subjects do not. The
-- unique constraint makes one provider account map to exactly one local user.
CREATE TABLE social_identities (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL,
    provider        varchar(16) NOT NULL,
    subject         varchar(255) NOT NULL,
    email_at_link   varchar(255),
    created_at      timestamp(6) with time zone NOT NULL,
    last_login_at   timestamp(6) with time zone,
    CONSTRAINT social_identities_provider_check
        CHECK (provider IN ('google', 'microsoft', 'apple')),
    CONSTRAINT fk_social_identities_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE UNIQUE INDEX ux_social_identity ON social_identities (provider, subject);
CREATE INDEX ix_social_identities_user ON social_identities (user_id);
