-- Resume positions, server-side bookmarks and friendships.

-- One row per (user, title, episode): the player upserts into it every few
-- seconds, so it is written far more often than it is read.
CREATE TABLE watch_progress (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL,
    anime_key         varchar(120) NOT NULL,
    anime_title       varchar(255),
    episode           integer NOT NULL,
    position_seconds  integer NOT NULL,
    duration_seconds  integer,
    completed         boolean NOT NULL DEFAULT false,
    provider          varchar(64),
    created_at        timestamp(6) with time zone NOT NULL,
    updated_at        timestamp(6) with time zone NOT NULL,
    CONSTRAINT watch_progress_position_check CHECK (position_seconds >= 0),
    CONSTRAINT watch_progress_episode_check CHECK (episode >= 0),
    CONSTRAINT fk_watch_progress_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE UNIQUE INDEX ux_watch_progress_slot
    ON watch_progress (user_id, anime_key, episode);
-- Drives "continue watching": newest unfinished rows for one user.
CREATE INDEX ix_watch_progress_recent
    ON watch_progress (user_id, completed, updated_at DESC);

CREATE TABLE bookmarks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,
    anime_id    bigint NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_bookmarks_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_bookmarks_anime FOREIGN KEY (anime_id) REFERENCES animes (id)
);

CREATE UNIQUE INDEX ux_bookmark_slot ON bookmarks (user_id, anime_id);
CREATE INDEX ix_bookmarks_user_recent ON bookmarks (user_id, created_at DESC);

CREATE TABLE friendships (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id  bigint NOT NULL,
    addressee_id  bigint NOT NULL,
    status        varchar(16) NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    responded_at  timestamp(6) with time zone,
    CONSTRAINT friendships_status_check
        CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED')),
    CONSTRAINT friendships_no_self CHECK (requester_id <> addressee_id),
    CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES app_users (id),
    CONSTRAINT fk_friendships_addressee FOREIGN KEY (addressee_id) REFERENCES app_users (id)
);

-- One edge per pair regardless of who asked: without the LEAST/GREATEST pair the
-- two directions could both exist and "are we friends?" would have two answers.
CREATE UNIQUE INDEX ux_friendship_pair
    ON friendships (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id));
CREATE INDEX ix_friendships_addressee ON friendships (addressee_id, status);
CREATE INDEX ix_friendships_requester ON friendships (requester_id, status);
