-- Country access rules. A row exists only for countries an operator touched;
-- absence means "allowed", so the default posture is open and an empty table
-- cannot accidentally lock the whole world out.
CREATE TABLE geo_rules (
    country_code  char(2) PRIMARY KEY,
    blocked       boolean NOT NULL DEFAULT true,
    note          varchar(255),
    updated_by    bigint,
    updated_at    timestamp(6) with time zone NOT NULL,
    CONSTRAINT geo_rules_code_upper CHECK (country_code = upper(country_code)),
    CONSTRAINT fk_geo_rules_admin FOREIGN KEY (updated_by) REFERENCES app_users (id)
);

-- Append-only trail: who changed which country, and how. Blocking a market is a
-- business decision someone will have to answer for later.
CREATE TABLE geo_audit (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code  char(2) NOT NULL,
    blocked       boolean NOT NULL,
    note          varchar(255),
    actor_id      bigint,
    actor_email   varchar(255),
    created_at    timestamp(6) with time zone NOT NULL
);

CREATE INDEX ix_geo_audit_recent ON geo_audit (created_at DESC);
