-- Personal scores. One score per (user, title), replaced on change — a rating is
-- a current opinion, not an event log, so there is no history to accumulate.
CREATE TABLE anime_ratings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,
    anime_id    bigint NOT NULL,
    score       smallint NOT NULL,
    review      varchar(500),
    country     varchar(2),
    created_at  timestamp(6) with time zone NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT anime_ratings_score_check CHECK (score BETWEEN 1 AND 10),
    CONSTRAINT fk_anime_ratings_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_anime_ratings_anime FOREIGN KEY (anime_id) REFERENCES animes (id)
);

CREATE UNIQUE INDEX ux_anime_rating_slot ON anime_ratings (user_id, anime_id);
CREATE INDEX ix_anime_ratings_anime ON anime_ratings (anime_id);
CREATE INDEX ix_anime_ratings_country ON anime_ratings (country);
